name: Build Virastyar Word Add-in

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Framework 4.8
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore VirastyarWordAddin.sln

      - name: Build solution
        run: msbuild VirastyarWordAddin.sln /p:Configuration=Release

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: virastyar-installer
          path: |
            VirastyarWordAddin\bin\Release\*.dll
            VirastyarWordAddin\bin\Release\VirastyarWordAddin.vsto
